import categoryDog from '../../client/src/images/adopt-dog.jpeg';
import categoryCat from '../../client/src/images/adopt-cat.jpeg';

export const categories = [
  {
    id: 1,
    img: categoryDog,
    title: 'HONDEN',
    desc: 'Het beste hondenras is een geredde hond.',
    cat: 'dog',
  },
  {
    id: 2,
    img: categoryCat,
    title: 'KATTEN',
    desc: 'Tijd doorgebracht met katten wordt nooit verspild.',
    cat: 'cat',
  },
];

export const pets = [
  {
    id: 1,
    category: 'dog',
    img: 'https://verhuisdieren.nl/images/profile-picture/1632475559-gAVewm6roa.png',
    city: 'Brummen',
    age: '5 maanden',
    name: 'Baloe',
    sex: 'female',
    size: 'Middel',
  },
  {
    id: 2,
    category: 'dog',
    img: 'https://verhuisdieren.nl/images/profile-picture/1603120082-xtk1n33wle.png',
    city: 'Amsterdam',
    age: '10 maanden',
    name: 'Shnitsel',
    sex: 'female',
    size: 'Middel',
  },
  {
    id: 3,
    category: 'cat',
    img: 'https://verhuisdieren.nl/images/profile-picture/1631966571-HRpnQusmqr.png',
    city: 'Rotterdam',
    age: '5 maanden',
    name: 'Lola',
    sex: 'female',
    size: 'Middel',
  },
  {
    id: 1,
    category: 'dog',
    img: 'https://i.ibb.co/XsdmR2c/1.png',
    city: 'Brummen',
    age: '5 maanden',
    name: 'Baloe',
    sex: 'female',
    size: 'Middel',
  },
  {
    id: 2,
    category: 'dog',
    img: 'https://i.ibb.co/XsdmR2c/1.png',
    city: 'Amsterdam',
    age: '10 maanden',
    name: 'Shnitsel',
    sex: 'female',
    size: 'Middel',
  },
  {
    id: 3,
    category: 'dog',
    img: 'https://i.ibb.co/XsdmR2c/1.png',
    city: 'Rotterdam',
    age: '5 maanden',
    name: 'Lola',
    sex: 'female',
    size: 'Middel',
  },
  {
    id: 1,
    category: 'dog',
    img: 'https://i.ibb.co/XsdmR2c/1.png',
    city: 'Brummen',
    age: '5 maanden',
    name: 'Baloe',
    sex: 'female',
    size: 'Middel',
  },
  {
    id: 2,
    category: 'dog',
    img: 'https://i.ibb.co/XsdmR2c/1.png',
    city: 'Amsterdam',
    age: '10 maanden',
    name: 'Shnitsel',
    sex: 'female',
    size: 'Middel',
  },
  {
    id: 3,
    type: 'dog',
    img: 'https://i.ibb.co/XsdmR2c/1.png',
    city: 'Rotterdam',
    age: '5 maanden',
    name: 'Lola',
    sex: 'female',
    size: 'Middel',
  },
  {
    id: 1,
    type: 'dog',
    img: 'https://i.ibb.co/XsdmR2c/1.png',
    city: 'Brummen',
    age: '5 maanden',
    name: 'Baloe',
    sex: 'female',
    size: 'Middel',
  },
  {
    id: 2,
    type: 'dog',
    img: 'https://i.ibb.co/XsdmR2c/1.png',
    city: 'Amsterdam',
    age: '10 maanden',
    name: 'Shnitsel',
    sex: 'female',
    size: 'Middel',
  },
  {
    id: 3,
    type: 'dog',
    img: 'https://i.ibb.co/XsdmR2c/1.png',
    city: 'Rotterdam',
    age: '5 maanden',
    name: 'Lola',
    sex: 'female',
    size: 'Middel',
  },
  {
    id: 1,
    type: 'dog',
    img: 'https://i.ibb.co/XsdmR2c/1.png',
    city: 'Brummen',
    age: '5 maanden',
    name: 'Baloe',
    sex: 'female',
    size: 'Middel',
  },
  {
    id: 2,
    type: 'dog',
    img: 'https://i.ibb.co/XsdmR2c/1.png',
    city: 'Amsterdam',
    age: '10 maanden',
    name: 'Shnitsel',
    sex: 'female',
    size: 'Middel',
  },
  {
    id: 3,
    type: 'dog',
    img: 'https://i.ibb.co/XsdmR2c/1.png',
    city: 'Rotterdam',
    age: '5 maanden',
    name: 'Lola',
    sex: 'female',
    size: 'Middel',
  },
  {
    id: 1,
    type: 'dog',
    img: 'https://i.ibb.co/XsdmR2c/1.png',
    city: 'Brummen',
    age: '5 maanden',
    name: 'Baloe',
    sex: 'female',
    size: 'Middel',
  },
  {
    id: 2,
    type: 'dog',
    img: 'https://i.ibb.co/XsdmR2c/1.png',
    city: 'Amsterdam',
    age: '10 maanden',
    name: 'Shnitsel',
    sex: 'female',
    size: 'Middel',
  },
  {
    id: 3,
    type: 'dog',
    img: 'https://i.ibb.co/XsdmR2c/1.png',
    city: 'Rotterdam',
    age: '5 maanden',
    name: 'Lola',
    sex: 'female',
    size: 'Middel',
  },
  {
    id: 1,
    type: 'dog',
    img: 'https://i.ibb.co/XsdmR2c/1.png',
    city: 'Brummen',
    age: '5 maanden',
    name: 'Baloe',
    sex: 'female',
    size: 'Middel',
  },
  {
    id: 2,
    type: 'dog',
    img: 'https://i.ibb.co/XsdmR2c/1.png',
    city: 'Amsterdam',
    age: '10 maanden',
    name: 'Shnitsel',
    sex: 'female',
    size: 'Middel',
  },
  {
    id: 3,
    type: 'dog',
    img: 'https://i.ibb.co/XsdmR2c/1.png',
    city: 'Rotterdam',
    age: '5 maanden',
    name: 'Lola',
    sex: 'female',
    size: 'Middel',
  },
  {
    id: 1,
    type: 'dog',
    img: 'https://i.ibb.co/XsdmR2c/1.png',
    city: 'Brummen',
    age: '5 maanden',
    name: 'Baloe',
    sex: 'female',
    size: 'Middel',
  },
  {
    id: 2,
    type: 'dog',
    img: 'https://i.ibb.co/XsdmR2c/1.png',
    city: 'Amsterdam',
    age: '10 maanden',
    name: 'Shnitsel',
    sex: 'female',
    size: 'Middel',
  },
  {
    id: 3,
    type: 'dog',
    img: 'https://i.ibb.co/XsdmR2c/1.png',
    city: 'Rotterdam',
    age: '5 maanden',
    name: 'Lola',
    sex: 'female',
    size: 'Middel',
  },
  {
    id: 1,
    type: 'dog',
    img: 'https://i.ibb.co/XsdmR2c/1.png',
    city: 'Brummen',
    age: '5 maanden',
    name: 'Baloe',
    sex: 'female',
    size: 'Middel',
  },
  {
    id: 2,
    type: 'dog',
    img: 'https://i.ibb.co/XsdmR2c/1.png',
    city: 'Amsterdam',
    age: '10 maanden',
    name: 'Shnitsel',
    sex: 'female',
    size: 'Middel',
  },
  {
    id: 3,
    type: 'dog',
    img: 'https://i.ibb.co/XsdmR2c/1.png',
    city: 'Rotterdam',
    age: '5 maanden',
    name: 'Lola',
    sex: 'female',
    size: 'Middel',
  },
  {
    id: 1,
    type: 'dog',
    img: 'https://i.ibb.co/XsdmR2c/1.png',
    city: 'Brummen',
    age: '5 maanden',
    name: 'Baloe',
    sex: 'female',
    size: 'Middel',
  },
  {
    id: 2,
    type: 'dog',
    img: 'https://i.ibb.co/XsdmR2c/1.png',
    city: 'Amsterdam',
    age: '10 maanden',
    name: 'Shnitsel',
    sex: 'female',
    size: 'Middel',
  },
  {
    id: 3,
    type: 'dog',
    img: 'https://i.ibb.co/XsdmR2c/1.png',
    city: 'Rotterdam',
    age: '5 maanden',
    name: 'Lola',
    sex: 'female',
    size: 'Middel',
  },
];
